- job:
    name: calculator_job1
    run: playbooks/calculator_job1.yaml
- job:
    name: calculator_test_job
    run: playbooks/calculator_test_job.yaml
- job:
    name: testjob2
    run: playbooks/testjob2.yaml
- job:
    name: testjob
    run: playbooks/testjob.yaml

- project:
    check:
      jobs:
        - calculator_job1
        - calculator_test_job
        - testjob2
        - testjob
        
- project:
    check:
      jobs:
        - noop

      
        
