- project:
    check:
      jobs:
        - noop
        
- project:
    name: devops-zuul/zuul-test
    check:
      jobs:
        - noop
        - testjob1
        
- job:
    name: testjob1
    run: testjob1.yaml

        


      
        
